[information]
 name = "autumnull"
 background = "dark"
 author = 'Kirixetamine <revelation@krxt.dev>'

[palette]
 fg = '#FFFEF7'
 bg = '#2A242D'

 alt_fg = '#FFFAF5'
 #alt_bg = '#403943'
 alt_bg = '#1F1922'
 dark = '#3F3842'
 accent = '#88798F'
 line = '#4B434F'
 light_gray = '#887F8F'
 tree_gray = '#6E595F'

 white = '#FFFEF7'
 gray = '#88798F'
 blue = '#9AD1FF'
 vivid_blue = '#399BFF'
 dark_blue = '#3800F3'
 light_blue = '#FFFEF7'
 green = '#9BF97E'
 light_green = '#DBFF9A'
 cyan = '#9BF3E1'
 #red = '#FF4550'
 #red = '#FF455E'
 #red = '#FF4671'
 red = '#FF4783'
 vivid_red = '#FF2839'
 light_red = '#FF736A'
 orange = '#FFA25E'
 dark_orange = '#FF6700'
 yellow = '#FFCE58'
 purple = '#7B7EFF'
 alt_purple = '#8F78FF'
 magenta = '#FFA0FF'

 cursor_fg = '#4E4552'
 cursor_bg = '#C5B0CF'

 sign_add = '#9BF97E'
 sign_change = '#FFA25E'
 sign_delete = '#FF4550'

 error_red = '#FF4550'
 info_purple = '#8F78FF'
 warning_orange = '#FFA25E'
 hint_yellow = '#FFD73F'
 success_green = "#D3ED80"

 ui_orange = '#FFA25E'
 ui_purple = '#7B7EFF'
 ui2_purple = '#8F78FF'
 ui3_purple = '#AF68FF'
 ui4_purple = '#D056FF'
 folder_purple = '#8F78FF'

 search_purple = '#AF68FF'
 search_orange = '#FFA25E'

 [highlights]
  Normal = 'fg bg'
  SignColumn = '- bg'
  MsgArea = 'fg bg'
  ModeMsg = 'fg dark'
  MsgSeparator = 'fg bg'
  WinSeparator = 'gray -'
  SpellBad = 'error_red - u'
  SpellCap = 'warning_orange - u'
  SpellLocal = 'green - u'
  SpellRare = 'magenta - u'
  NormalNC = 'fg bg'
  WildMenu = 'fg ui2_purple'
  Comment = 'gray - i'
  Folded = 'accent alt_bg'
  FoldColumn = 'accent alt_bg'
  LineNr = 'gray -'
  FloatBorder = 'gray alt_bg'
  Whitespace = 'bg -'
  CursorLine = '- dark'
  CursorLineNr = '- dark'
  CursorColumn = '- dark'
  ColorColumn = '- dark'
  NormalFloat = '- dark'
  Visual = 'ui2_purple dark'
  VisualNOS = '- alt_bg'
  WarningMsg = 'error_red bg'
  DiffAdd = 'alt_bg sign_add'
  DiffChange = 'alt_bg sign_change u'
  DiffDelete = 'alt_bg sign_delete'
  QuickFixLine = '- ui2_purple'
  Pmenu = 'fg alt_bg'
  PmenuSel = '- line'
  PmenuSbar = '- alt_bg'
  PmenuThumb = '- gray'
  MatchWord = '- - u'
  MatchParen = 'hint_yellow bg u'
  MatchWordCur = '- - u'
  MatchParenCur = '- - u'
  Cursor = 'cursor_fg cursor_bg'
  lCursor = 'cursor_fg cursor_bg'
  CursorIM = 'cursor_fg cursor_bg'
  TermCursor = 'cursor_fg cursor_bg'
  TermCursorNC = 'cursor_fg cursor_bg'
  Conceal = 'accent'
  Directory = 'yellow'
  SpecialKey = 'yellow - b'
  Title = 'yellow - b'
  ErrorMsg = 'error_red bg b'
  Search = 'light_gray search_blue'
  IncSearch = 'search_orange light_gray'
  Substitute = 'light_gray search_orange'
  MoreMsg = 'orange'
  Question = 'orange'
  EndOfBuffer = 'bg'
  NonText = 'bg'
  Variable = 'light_red'
  String = 'yellow'
  Character = 'yellow'
  Constant = 'purple'
  Number = 'purple'
  Boolean = 'purple'
  Float = 'purple'
  Identifier = 'light_red'
  Function = 'green'
  Operator = 'fg'
  Type = 'orange'
  StorageClass = 'red'
  Structure = 'red'
  Typedef = 'red - i'
  Keyword = 'red - i'
  Statement = 'purple'
  Conditional = 'red'
  Repeat = 'red'
  Label = 'red'
  Exception = 'red'
  Include = 'red'
  PreProc = 'red'
  Define = 'red'
  Macro = 'light_red'
  PreCondit = 'red'
  Special = 'red'
  SpecialChar = 'white'
  Tag = 'yellow'
  Debug = 'red'
  Delimiter = 'gray -'
  SpecialComment = 'gray'
  Underlined = '- - u'
  Bold = '- - b'
  Italic = '- - i'
  Ignore = 'cyan bg b'
  Todo = 'magenta bg b'
  Error = 'error_red bg b'
  TabLine = 'light_gray line'
  TabLineSel = 'white line'
  TabLineFill = 'line line'

[Buffer]
  BufferCurrent = 'fg bg'
  BufferCurrentIndex = 'fg bg'
  BufferCurrentMod = 'info_purple bg'
  BufferCurrentSign = 'hint_yellow bg'
  BufferCurrentTarget = 'red bg b'

  BufferVisible = 'fg bg'
  BufferVisibleIndex = 'fg bg'
  BufferVisibleMod = 'info_purple bg'
  BufferVisibleSign = 'gray bg'
  BufferVisibleTarget = 'red bg b'

  BufferInactive = 'gray alt_bg'
  BufferInactiveIndex = 'gray alt_bg'
  BufferInactiveMod = 'info_purple alt_bg'
  BufferInactiveSign = 'gray alt_bg'
  BufferInactiveTarget = 'red alt_bg b'

[Cmp]
  CmpItemMenu = '- alt_bg i'
  CmpItemAbbrDeprecated = 'gray - s'
  CmpItemAbbrMatch = 'ui3_purple'
  CmpItemKindFunction = 'red'
  CmpItemKindMethod = 'red'
  CmpItemKindConstructor = 'purple'
  CmpItemKindClass = 'purple'
  CmpItemKindEnum = 'purple'
  CmpItemKindEvent = 'yellow'
  CmpItemKindInterface = 'red'
  CmpItemKindStruct = 'red'
  CmpItemKindVariable = 'orange'
  CmpItemKindField = 'orange'
  CmpItemKindProperty = 'orange'
  CmpItemKindEnumMember = 'orange'
  CmpItemKindConstant = 'light_red'
  CmpItemKindKeyword = 'light_red'
  CmpItemKindModule = 'purple'
  CmpItemKindValue = 'fg'
  CmpItemKindUnit = 'fg'
  CmpItemKindText = 'fg'
  CmpItemKindSnippet = 'yellow'
  CmpItemKindFile = 'fg'
  CmpItemKindFolder = 'fg'
  CmpItemKindColor = 'fg'
  CmpItemKindReference = 'fg'
  CmpItemKindOperator = 'fg'
  CmpItemKindTypeParameter = 'red'

[Git]
  SignAdd = 'sign_add'
  SignChange = 'sign_change'
  SignDelete = 'sign_delete'
  GitSignsAdd = 'sign_add'
  GitSignsChange = 'sign_change'
  GitSignsDelete = 'sign_delete'

[IndentBlankline]
  IndentBlanklineChar = 'dark'
  IndentBlanklineContextChar = 'gray'
  IndentBlanklineContextStart = 'yellow - i'
  IndentBlanklineSpaceChar = '-'
  IndentBlanklineSpaceCharBlankline = '-'

[Lsp]
  DiagnosticSignError = 'error_red'
  DiagnosticSignWarning = 'warning_orange'
  DiagnosticSignInformation = 'info_purple'
  DiagnosticSignInfo = 'info_purple'
  DiagnosticSignHint = 'hint_yellow'
  LspDiagnosticsDefaultError = 'error_red'
  LspDiagnosticsDefaultWarning = 'warning_orange'
  LspDiagnosticsDefaultInformation = 'info_purple'
  LspDiagnosticsDefaultInfo = 'info_purple'
  LspDiagnosticsDefaultHint = 'hint_yellow'
  LspDiagnosticsSignError = 'error_red'
  LspDiagnosticsSignWarning = 'warning_orange'
  LspDiagnosticsSignInformation = 'info_purple'
  LspDiagnosticsSignInfo = 'info_purple'
  LspDiagnosticsSignHint = 'hint_yellow'
  LspDiagnosticsError = 'error_red'
  LspDiagnosticsWarning = 'warning_orange'
  LspDiagnosticsInformation = 'info_purple'
  LspDiagnosticsInfo = 'info_purple'
  LspDiagnosticsHint = 'hint_yellow'
  LspDiagnosticsUnderlineError = '- - u'
  LspDiagnosticsUnderlineWarning = '- - u'
  LspDiagnosticsUnderlineInformation = '- - u'
  LspDiagnosticsUnderlineInfo = '- - u'
  LspDiagnosticsUnderlineHint = '- - u'
  LspDiagnosticsVirtualTextError = 'error_red'
  LspDiagnosticsVirtualTextWarning = 'warning_orange'
  LspDiagnosticsVirtualTextInformation = 'info_purple'
  LspDiagnosticsVirtualTextInfo = 'info_purple'
  LspDiagnosticsVirtualTextHint = 'hint_yellow'
  LspDiagnosticsFloatingError = 'error_red'
  LspDiagnosticsFloatingWarning = 'warning_orange'
  LspDiagnosticsFloatingInformation = 'info_purple'
  LspDiagnosticsFloatingInfo = 'info_purple'
  LspDiagnosticsFloatingHint = 'hint_yellow'
  LspReferenceRead = '- alt_bg'
  LspReferenceText = '- alt_bg'
  LspReferenceWrite = '- alt_bg'
  LspCodeLens = 'gray - i'
  LspCodeLensSeparator = 'gray - i'

[NvimTree]
  NvimTreeCursorLine = '- line'
  NvimTreeEmptyFolderName = 'gray - i'
  NvimTreeEndOfBuffer = 'tree_gray'
  NvimTreeFolderIcon = 'folder_blue'
  NvimTreeFolderName = 'folder_blue'
  NvimTreeGitDeleted = 'sign_delete'
  NvimTreeGitDirty = 'sign_change'
  NvimTreeGitIgnored = 'gray - i'
  NvimTreeGitignoreIcon = 'light_red'
  NvimTreeGitMerge = 'sign_change'
  NvimTreeGitNew = 'sign_add'
  NvimTreeGitRenamed = 'sign_add'
  NvimTreeGitStaged = 'sign_add'
  NvimTreeImageFile = 'light_gray'
  NvimTreeIndentMarker = '#c5c5c5'
  NvimTreeNormal = 'fg alt_bg'
  NvimTreeOpenedFolderName = 'folder_blue - bi'
  NvimTreeSpecialFile = 'orange'
  NvimTreeVertSplit = 'alt_bg alt_bg'

[Statusline]
  StatusLine = 'line dark'
  StatusLineNC = 'dark line'
  StatusLineSeparator = 'line'
  StatusLineTerm = 'line'
  StatusLineTermNC = 'line'

[Telescope]
  TelescopeSelection = 'hint_yellow'
  TelescopeMatching = 'info_purple - b'
  TelescopeBorder = 'purple bg'

[Treesitter]
 TreesitterContext = '- tree_gray'
 TSAnnotation = 'purple'
 TSAttribute = 'cyan'
 TSBoolean = 'purple'
 TSCharacter = 'yellow'
 TSComment = 'link:Comment'
 TSConditional = 'yellow'
 TSConstant = 'purple'
 TSConstBuiltin = 'purple'
 TSConstMacro = 'purple'
 TSConstructor = 'cyan'
 TSEmphasis = '- - i'
 TSError = 'error_red'
 TSException = 'warning_orange'
 TSField = 'fg'
 TSFloat = 'purple'
 TSFuncBuiltin = 'light_red'
 TSFuncMacro = 'light_red'
 TSFunction = 'green'
 TSInclude = 'purple'
 TSKeywordFunction = 'purple'
 TSKeywordOperator = 'purple'
 TSKeyword = 'purple'
 TSKeywordReturn = 'purple'
 TSLabel = 'light_blue'
 TSLiteral = 'orange'
 TSMethod = 'blue'
 TSNamespace = 'cyan'
 TSNumber = 'orange'
 TSOperator = 'alt_fg'
 TSParameter = 'red'
 TSParameterReference = 'red'
 TSProperty = 'red'
 TSPunctBracket = 'alt_fg -'
 TSPunctDelimiter = 'alt_fg -'
 TSPunctSpecial = 'purple'
 TSQueryLinterError = 'warning_orange'
 TSRepeat = 'yellow'
 TSStringEscape = 'green'
 TSString = 'green'
 TSStringRegex = 'green'
 TSStrong = 'purple - b'
 TSStructure = 'red'
 TSSymbol = 'red'
 TSTagAttribute = 'orange'
 TSTag = 'blue'
 TSTagDelimiter = 'alt_fg'
 TSText = 'alt_fg'
 TSTitle = 'fg - -'
 TSTypeBuiltin = 'orange'
 TSType = 'cyan'
 TSUnderline = '- - u'
 TSURI = 'orange - u'
 TSVariableBuiltin = 'red'
 TSVariable = 'light_red'

[Whichkey]
  WhichKey = 'purple'
  WhichKeySeperator = 'green'
  WhichKeyGroup = 'blue'
  WhichKeyDesc = 'light_red'
  WhichKeyFloat = '- dark'
