[information]
 name = "autumnull"
 background = "dark"
 author = 'Kirixetamine <revelation@krxt.dev>'

[palette]
 fg = '#FFFEF7'
 bg = '#2A242D'

 alt_fg = '#FFFAF5'
 alt_bg = '#403943'
 dark = '#3F3842'
 accent = '#88798F'
 line = '#4B434F'
 light_gray = '#887F8F'

 white = '#FFFEF7'
 gray = '#88798F'
 blue = '#9AD1FF'
 vivid_blue = '#399BFF'
 dark_blue = '#3800F3'
 folder_blue = '#0081FF'
 light_blue = '#FFFEF7'
 green = '#D3ED80'
 light_green = '#DBFF9A'
 cyan = '#9BF3E1'
 red = '#FF4550'
 vivid_red = '#FF2839'
 light_red = '#FF736A'
 orange = '#FFA25E'
 dark_orange = '#FF6700'
 yellow = '#FFCE58'
 purple = '#D056FF'
 magenta = '#FFA0FF'

 cursor_fg = '#4E4552'
 cursor_bg = '#C5B0CF'

 sign_add = '#D3ED80'
 sign_change = '#9AD1FF'
 sign_delete = '#FF4550'

 error_red = '#FF4550'
 warning_orange = '#FFA25E'
 hint_blue = '#9AD1FF'
 success_green = "#D3ED80"

 ui_blue = '#9AD1FF'
 ui2_blue = '#3800F3'
 ui3_blue = '#399BFF'
 ui4_blue = '#C0EDFF'
 ui_orange = '#FFA25E'
 ui_purple = '#D056FF'

 search_blue = '#3800F3'
 search_orange = '#FFA25E'

 [highlights]
  Normal = 'fg bg'
  SignColumn = '- bg'
  MsgArea = 'fg bg'
  ModeMsg = 'fg dark'
  MsgSeparator = 'fg bg'
  SpellBad = 'red - u'
  SpellCap = 'yellow - u'
  SpellLocal = 'green - u'
  SpellRare = 'magenta - u'
  NormalNC = 'fg bg'
  Comment = 'gray - i'
  Folded = 'accent alt_bg'
  FoldColumn = 'accent alt_bg'
  LineNr = 'gray -'
  FloatBorder = 'gray alt_bg'
  Whitespace = 'bg -'
  CursorLine = '- dark'
  CursorLineNr = '- dark'
  CursorColumn = '- dark'
  ColorColumn = '- dark'
  NormalFloat = '- dark'
  Visual = '- light_gray'
  VisualNOS = '- alt_bg'
  WarningMsg = 'error_red bg'
  DiffAdd = 'alt_bg sign_add'
  DiffChange = 'alt_bg sign_change u'
  DiffDelete = 'alt_bg sign_delete'
  QuickFixLine = '- ui2_blue'
  PmenuSbar = '- alt_bg'
  PmenuThumb = '- gray'
  MatchWord = '- - u'
  MatchParen = 'hint_blue bg u'
  MatchWordCur = '- - u'
  MatchParenCur = '- - u'
  Cursor = 'cursor_fg cursor_bg'
  lCursor = 'cursor_fg cursor_bg'
  CursorIM = 'cursor_fg cursor_bg'
  TermCursor = 'cursor_fg cursor_bg'
  TermCursorNC = 'cursor_fg cursor_bg'
  Conceal = 'accent'
  Directory = 'blue'
  SpecialKey = 'blue - b'
  Title = 'blue - b'
  ErrorMsg = 'error_red bg b'
  Search = 'light_gray search_blue'
  IncSearch = 'search_orange light_gray'
  Substitute = 'light_gray search_orange'
  MoreMsg = 'orange'
  Question = 'orange'
  EndOfBuffer = 'bg'
  NonText = 'bg'
  Variable = 'light_blue'
  String = 'orange'
  Character = 'orange'
  Constant = 'vivid_blue'
  Number = 'light_green'
  Boolean = 'blue'
  Float = 'light_green'
  Identifier = 'light_blue'
  Function = 'yellow'
  Operator = 'fg'
  Type = 'cyan'
  StorageClass = 'blue'
  Structure = 'blue'
  Typedef = 'blue'
  Keyword = 'blue'
  Statement = 'purple'
  Conditional = 'blue'
  Repeat = 'purple'
  Label = 'purple'
  Exception = 'purple'
  Include = 'purple'
  PreProc = 'purple'
  Define = 'purple'
  Macro = 'purple'
  PreCondit = 'purple'
  Special = 'orange'
  SpecialChar = 'white'
  Tag = 'blue'
  Debug = 'red'
  Delimiter = 'gray -'
  SpecialComment = 'gray'
  Underlined = '- - u'
  Bold = '- - b'
  Italic = '- - i'
  Ignore = 'cyan bg b'
  Todo = 'magenta bg b'
  Error = 'error_red bg b'
  TabLine = 'light_gray line'
  TabLineSel = 'white line'
  TabLineFill = 'line line'
