local c = require('autumnull.palette')

local hl = vim.api.nvim_set_hl
local theme = {}

theme.set_highlights = function()

  -- highlights
  hl(0, "Normal", { fg = c.fg, bg = c.bg, })
  hl(0, "SignColumn", { fg = 'NONE', bg = c.bg, })
  hl(0, "MsgArea", { fg = c.fg, bg = c.bg, })
  hl(0, "ModeMsg", { fg = c.fg, bg = c.dark, })
  hl(0, "MsgSeparator", { fg = c.fg, bg = c.bg, })
  hl(0, "SpellBad", { fg = c.error_red, bg = 'NONE', underline=true, })
  hl(0, "SpellCap", { fg = c.warning_orange, bg = 'NONE', underline=true, })
  hl(0, "SpellLocal", { fg = c.green, bg = 'NONE', underline=true, })
  hl(0, "SpellRare", { fg = c.magenta, bg = 'NONE', underline=true, })
  hl(0, "NormalNC", { fg = c.fg, bg = c.bg, })
  hl(0, "Comment", { fg = c.gray, bg = 'NONE', italic=true, })
  hl(0, "Folded", { fg = c.accent, bg = c.alt_bg, })
  hl(0, "FoldColumn", { fg = c.accent, bg = c.alt_bg, })
  hl(0, "LineNr", { fg = c.gray, bg = 'NONE', })
  hl(0, "FloatBorder", { fg = c.gray, bg = c.alt_bg, })
  hl(0, "Whitespace", { fg = c.bg, bg = 'NONE', })
  hl(0, "CursorLine", { fg = 'NONE', bg = c.dark, })
  hl(0, "CursorLineNr", { fg = 'NONE', bg = c.dark, })
  hl(0, "CursorColumn", { fg = 'NONE', bg = c.dark, })
  hl(0, "ColorColumn", { fg = 'NONE', bg = c.dark, })
  hl(0, "NormalFloat", { fg = 'NONE', bg = c.dark, })
  hl(0, "Visual", { fg = 'NONE', bg = c.light_gray, })
  hl(0, "VisualNOS", { fg = 'NONE', bg = c.alt_bg, })
  hl(0, "WarningMsg", { fg = c.error_red, bg = c.bg, })
  hl(0, "DiffAdd", { fg = c.alt_bg, bg = c.sign_add, })
  hl(0, "DiffChange", { fg = c.alt_bg, bg = c.sign_change, underline=true, })
  hl(0, "DiffDelete", { fg = c.alt_bg, bg = c.sign_delete, })
  hl(0, "QuickFixLine", { fg = 'NONE', bg = c.ui2_blue, })
  hl(0, "PmenuSbar", { fg = 'NONE', bg = c.alt_bg, })
  hl(0, "PmenuThumb", { fg = 'NONE', bg = c.gray, })
  hl(0, "MatchWord", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "MatchParen", { fg = c.hint_yellow, bg = c.bg, underline=true, })
  hl(0, "MatchWordCur", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "MatchParenCur", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "Cursor", { fg = c.cursor_fg, bg = c.cursor_bg, })
  hl(0, "lCursor", { fg = c.cursor_fg, bg = c.cursor_bg, })
  hl(0, "CursorIM", { fg = c.cursor_fg, bg = c.cursor_bg, })
  hl(0, "TermCursor", { fg = c.cursor_fg, bg = c.cursor_bg, })
  hl(0, "TermCursorNC", { fg = c.cursor_fg, bg = c.cursor_bg, })
  hl(0, "Conceal", { fg = c.accent, bg = 'NONE', })
  hl(0, "Directory", { fg = c.yellow, bg = 'NONE', })
  hl(0, "SpecialKey", { fg = c.yellow, bg = 'NONE', bold=true, })
  hl(0, "Title", { fg = c.yellow, bg = 'NONE', bold=true, })
  hl(0, "ErrorMsg", { fg = c.error_red, bg = c.bg, bold=true, })
  hl(0, "Search", { fg = c.light_gray, bg = c.search_blue, })
  hl(0, "IncSearch", { fg = c.search_orange, bg = c.light_gray, })
  hl(0, "Substitute", { fg = c.light_gray, bg = c.search_orange, })
  hl(0, "MoreMsg", { fg = c.orange, bg = 'NONE', })
  hl(0, "Question", { fg = c.orange, bg = 'NONE', })
  hl(0, "EndOfBuffer", { fg = c.bg, bg = 'NONE', })
  hl(0, "NonText", { fg = c.bg, bg = 'NONE', })
  hl(0, "Variable", { fg = c.light_red, bg = 'NONE', })
  hl(0, "String", { fg = c.yellow, bg = 'NONE', })
  hl(0, "Character", { fg = c.yellow, bg = 'NONE', })
  hl(0, "Constant", { fg = c.purple, bg = 'NONE', })
  hl(0, "Number", { fg = c.purple, bg = 'NONE', })
  hl(0, "Boolean", { fg = c.purple, bg = 'NONE', })
  hl(0, "Float", { fg = c.light_green, bg = 'NONE', })
  hl(0, "Identifier", { fg = c.light_red, bg = 'NONE', })
  hl(0, "Function", { fg = c.green, bg = 'NONE', })
  hl(0, "Operator", { fg = c.fg, bg = 'NONE', })
  hl(0, "Type", { fg = c.orange, bg = 'NONE', })
  hl(0, "StorageClass", { fg = c.red, bg = 'NONE', })
  hl(0, "Structure", { fg = c.red, bg = 'NONE', })
  hl(0, "Typedef", { fg = c.red, bg = 'NONE', italic=true, })
  hl(0, "Keyword", { fg = c.red, bg = 'NONE', italic=true, })
  hl(0, "Statement", { fg = c.purple, bg = 'NONE', })
  hl(0, "Conditional", { fg = c.red, bg = 'NONE', })
  hl(0, "Repeat", { fg = c.red, bg = 'NONE', })
  hl(0, "Label", { fg = c.red, bg = 'NONE', })
  hl(0, "Exception", { fg = c.red, bg = 'NONE', })
  hl(0, "Include", { fg = c.red, bg = 'NONE', })
  hl(0, "PreProc", { fg = c.red, bg = 'NONE', })
  hl(0, "Define", { fg = c.red, bg = 'NONE', })
  hl(0, "Macro", { fg = c.light_red, bg = 'NONE', })
  hl(0, "PreCondit", { fg = c.red, bg = 'NONE', })
  hl(0, "Special", { fg = c.red, bg = 'NONE', })
  hl(0, "SpecialChar", { fg = c.white, bg = 'NONE', })
  hl(0, "Tag", { fg = c.yellow, bg = 'NONE', })
  hl(0, "Debug", { fg = c.red, bg = 'NONE', })
  hl(0, "Delimiter", { fg = c.gray, bg = 'NONE', })
  hl(0, "SpecialComment", { fg = c.gray, bg = 'NONE', })
  hl(0, "Underlined", { fg = 'NONE', bg = 'NONE', underline=true, })
  hl(0, "Bold", { fg = 'NONE', bg = 'NONE', bold=true, })
  hl(0, "Italic", { fg = 'NONE', bg = 'NONE', italic=true, })
  hl(0, "Ignore", { fg = c.cyan, bg = c.bg, bold=true, })
  hl(0, "Todo", { fg = c.magenta, bg = c.bg, bold=true, })
  hl(0, "Error", { fg = c.error_red, bg = c.bg, bold=true, })
  hl(0, "TabLine", { fg = c.light_gray, bg = c.line, })
  hl(0, "TabLineSel", { fg = c.white, bg = c.line, })
  hl(0, "TabLineFill", { fg = c.line, bg = c.line, })

  -- Buffer
  hl(0, "BufferCurrent", { fg = c.fg, bg = c.bg, })
  hl(0, "BufferCurrentIndex", { fg = c.fg, bg = c.bg, })
  hl(0, "BufferCurrentMod", { fg = c.info_purple, bg = c.bg, })
  hl(0, "BufferCurrentSign", { fg = c.hint_yellow, bg = c.bg, })
  hl(0, "BufferCurrentTarget", { fg = c.red, bg = c.bg, bold=true, })
  hl(0, "BufferVisible", { fg = c.fg, bg = c.bg, })
  hl(0, "BufferVisibleIndex", { fg = c.fg, bg = c.bg, })
  hl(0, "BufferVisibleMod", { fg = c.info_purple, bg = c.bg, })
  hl(0, "BufferVisibleSign", { fg = c.gray, bg = c.bg, })
  hl(0, "BufferVisibleTarget", { fg = c.red, bg = c.bg, bold=true, })
  hl(0, "BufferInactive", { fg = c.gray, bg = c.alt_bg, })
  hl(0, "BufferInactiveIndex", { fg = c.gray, bg = c.alt_bg, })
  hl(0, "BufferInactiveMod", { fg = c.info_purple, bg = c.alt_bg, })
  hl(0, "BufferInactiveSign", { fg = c.gray, bg = c.alt_bg, })
  hl(0, "BufferInactiveTarget", { fg = c.red, bg = c.alt_bg, bold=true, })

  -- Git
  hl(0, "SignAdd", { fg = c.sign_add, bg = 'NONE', })
  hl(0, "SignChange", { fg = c.sign_change, bg = 'NONE', })
  hl(0, "SignDelete", { fg = c.sign_delete, bg = 'NONE', })
  hl(0, "GitSignsAdd", { fg = c.sign_add, bg = 'NONE', })
  hl(0, "GitSignsChange", { fg = c.sign_change, bg = 'NONE', })
  hl(0, "GitSignsDelete", { fg = c.sign_delete, bg = 'NONE', })

  -- IndentBlankline
  hl(0, "IndentBlanklineChar", { fg = c.dark, bg = 'NONE', })
  hl(0, "IndentBlanklineContextChar", { fg = c.gray, bg = 'NONE', })
  hl(0, "IndentBlanklineContextStart", { fg = c.yellow, bg = 'NONE', underline=true, })

  -- Statusline
  hl(0, "StatusLine", { fg = c.line, bg = c.dark, })
  hl(0, "StatusLineNC", { fg = c.line, bg = c.dark, })
  hl(0, "StatusLineSeparator", { fg = c.line, bg = 'NONE', })
  hl(0, "StatusLineTerm", { fg = c.line, bg = 'NONE', })
  hl(0, "StatusLineTermNC", { fg = c.line, bg = 'NONE', })

  -- Whichkey
  hl(0, "WhichKey", { fg = c.purple, bg = 'NONE', })
  hl(0, "WhichKeySeperator", { fg = c.green, bg = 'NONE', })
  hl(0, "WhichKeyGroup", { fg = c.blue, bg = 'NONE', })
  hl(0, "WhichKeyDesc", { fg = c.light_red, bg = 'NONE', })
  hl(0, "WhichKeyFloat", { fg = 'NONE', bg = c.dark, })

end

return theme